version: '3.8'

services:
  api:
    image: node-16
    container_name: api-node
    restart: always
    ports:
      - "3333:3333"
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app
    environment:
      - PORT=3333
      - MONGO_URL=mongodb+srv://louisdev46:oitFG1cOREindeFF@cluster0.wjwd4.mongodb.net/myFirstDatabase?retryWrites=true&w=majority 


      