version: '3.8'

services:
  api:
    image: node-16
    container_name: api-node
    restart: always
    ports:
      - "3333:3333"
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app
    env_file:
      - .env


      